### ISSUE TITLE
Virus detected in download

### ISSUE THREAD

**Issue by eternauta123** [killerall/advpl-vscode#175]
![image](https://user-images.githubusercontent.com/34449118/36104070-0934fbf0-1022-11e8-8795-169cb8daee06.png)

**Comment by killerall** [comment]
Você poderia detalhar melhor o que o seu antivirus detectou?
E qual é o mesmo.
A algum tempo atras, tinhamos problema com o da Symantec.

**Comment by eternauta123** [comment]
![image](https://user-images.githubusercontent.com/34449118/36149875-819fa4cc-10d2-11e8-9b47-dec50ca48461.png)

**Comment by killerall** [comment]
É o mesmo problema da Symantec, se for possivel informe seu antivirus esta errado. (O Symantec tem opçao para isso).
know from my personal experience that various antivirus software including Windows Defender and SmartScreen frequently detect AdvplDebugBridge. This is mostly caused by the generic heuristic that recognizes patterns like unpacking compressed/encrypted executable and starting it as service that listens for incoming requests in combination with a "rare" binary (which it is for every new release).
